version: '3'
services:

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    volumes:
      - ./fluentbit:/fluent-bit/etc/

  #Nginx Service
  webserver-devel:
    #image:  tecob/nginx-brotli 
    image: nginx:latest
    container_name: webserver-devel
    restart: unless-stopped
    tty: true
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /home/devel/www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
    logging:
      driver: fluentd
      options:
        tag: nginx
    depends_on:
      - fluentbit
    networks:
      - devel-network
    links:
      - fluentbit
