scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['francrodriguez.com:8080']

  - job_name: 'nginx-website'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['francrodriguez.com:9113']

